export const skillRegistry = [
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    description: 'Inverts page colors to a dark theme using DarkReader or CSS fallback, with configurable brightness, contrast, sepia, and grayscale.',
    supportAreas: ['vision', 'sensory'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'dark_mode',
  },
  {
    id: 'focus-mode',
    name: 'Focus Mode',
    description: 'Dims distracting elements like ads and popups, optionally dims non-main content, highlights the paragraph you are reading, and shows a scroll progress bar.',
    supportAreas: ['cognitive', 'reading', 'sensory'],
    siteRelevance: ['news', 'education', 'social'],
    requiresAI: false,
    icon: 'center_focus_strong',
  },
  {
    id: 'visual-assist',
    name: 'Visual Assist',
    description: 'Adjustable font size, line height, letter spacing, large cursor, reading guide, enhanced focus indicators, dyslexia font, and high-contrast modes.',
    supportAreas: ['vision', 'reading'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'visibility',
  },
  {
    id: 'motion-reducer',
    name: 'Reduce Motion',
    description: 'Stops animations, GIFs, auto-playing videos (including YouTube/Vimeo iframes), and parallax scrolling to reduce visual stimulation.',
    supportAreas: ['sensory', 'cognitive', 'vision'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'motion_photos_pause',
  },
  {
    id: 'reader-mode',
    name: 'Reader Mode',
    description: 'Extracts the main article content and displays it in a clean, distraction-free overlay with XSS sanitization and byline extraction.',
    supportAreas: ['cognitive', 'reading', 'sensory'],
    siteRelevance: ['news', 'education'],
    requiresAI: false,
    icon: 'article',
  },
  {
    id: 'keyboard-nav',
    name: 'Keyboard Navigation',
    description: 'Adds skip links (main content and navigation), enhanced focus indicators, tab sequence overlay, and keyboard shortcuts (Alt+1/2/H/F).',
    supportAreas: ['motor', 'vision'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'keyboard',
  },
  {
    id: 'auto-alt-text',
    name: 'Auto Alt Text',
    description: 'Generates descriptive alt text for images, SVGs, canvas elements, and video frames using AI vision.',
    supportAreas: ['vision'],
    siteRelevance: ['all'],
    requiresAI: true,
    icon: 'image',
  },
  {
    id: 'fix-contrast',
    name: 'Fix Contrast',
    description: 'Detects text with poor color contrast and fixes it using AI color suggestions or black/white fallback to meet WCAG AA.',
    supportAreas: ['vision'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'contrast',
  },
  {
    id: 'simplify-text',
    name: 'Simplify Text',
    description: 'Rewrites complex text to a simpler reading level with a toggle to show the original, and adds summaries to long content.',
    supportAreas: ['cognitive', 'reading'],
    siteRelevance: ['news', 'education'],
    requiresAI: true,
    icon: 'edit_note',
  },
  {
    id: 'voice-commands',
    name: 'Voice Commands',
    description: 'Hands-free browsing with voice commands, visual feedback HUD, interim results, and an expandable command set.',
    supportAreas: ['motor'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'mic',
  },
  {
    id: 'auto-captions',
    name: 'Auto Captions',
    description: 'Live caption overlay for videos with CC toggle button, YouTube caption auto-enable, and MutationObserver for dynamically added media.',
    supportAreas: ['hearing'],
    siteRelevance: ['video', 'social', 'education'],
    requiresAI: false,
    icon: 'closed_caption',
  },
  {
    id: 'color-filter',
    name: 'Color Blind Filter',
    description: 'Applies SVG color correction filters for protanopia, deuteranopia, or tritanopia color vision deficiencies.',
    supportAreas: ['vision'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'palette',
  },
  {
    id: 'read-aloud',
    name: 'Read Aloud',
    description: 'Text-to-speech with word boundary tracking, voice selection, rate/pitch controls, and presets (slow, normal, fast).',
    supportAreas: ['vision', 'reading', 'cognitive'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'volume_up',
  },
  {
    id: 'generate-labels',
    name: 'Generate Labels',
    description: 'AI-powered label generation for unlabeled links, buttons, iframes, and form inputs using context inference and pattern matching.',
    supportAreas: ['vision', 'motor'],
    siteRelevance: ['all'],
    requiresAI: true,
    icon: 'label',
  },
  {
    id: 'generate-captions',
    name: 'Generate Captions',
    description: 'AI-powered caption generation for videos (WebVTT tracks) and audio elements (expandable transcripts).',
    supportAreas: ['hearing'],
    siteRelevance: ['video', 'education'],
    requiresAI: true,
    icon: 'subtitles',
  },
  {
    id: 'wcag-fixes',
    name: 'WCAG Auto-Fix',
    description: 'Automatic fixes for common WCAG violations: lang attributes, duplicate IDs, heading order, tabindex, ARIA validation, touch targets, and more.',
    supportAreas: ['vision', 'motor', 'cognitive'],
    siteRelevance: ['all'],
    requiresAI: false,
    icon: 'verified',
  },
];

export function getSkillById(id) {
  return skillRegistry.find(s => s.id === id);
}

export function getSkillsByArea(area) {
  return skillRegistry.filter(s => s.supportAreas.includes(area));
}

export function getRegistryForPrompt() {
  return skillRegistry.map(s => ({
    id: s.id,
    name: s.name,
    description: s.description,
    supportAreas: s.supportAreas,
    siteRelevance: s.siteRelevance,
  }));
}
